insert into building values (NULL, 'Airport');
insert into building values (NULL, 'Aqueduct');
insert into building values (NULL, 'Bank');
insert into building values (NULL, 'Barracks');
insert into building values (NULL, 'Capitalization');
insert into building values (NULL, 'Cathedral');
insert into building values (NULL, 'City Walls');
insert into building values (NULL, 'Coastal Fortress');
insert into building values (NULL, 'Colosseum');
insert into building values (NULL, 'Courthouse');
insert into building values (NULL, 'Factory');
insert into building values (NULL, 'Granary');
insert into building values (NULL, 'Harbor');
insert into building values (NULL, 'Hydro Plant');
insert into building values (NULL, 'Library');
insert into building values (NULL, 'Mfg. Plant');
insert into building values (NULL, 'Marketplace');
insert into building values (NULL, 'Mass Transit');
insert into building values (NULL, 'Nuclear Plant');
insert into building values (NULL, 'Offshore Platform');
insert into building values (NULL, 'Palace');
insert into building values (NULL, 'Police Station');
insert into building values (NULL, 'Port Facility');
insert into building values (NULL, 'Power Plant');
insert into building values (NULL, 'Recycling Center');
insert into building values (NULL, 'Research Lab');
insert into building values (NULL, 'SAM Missile Battery');
insert into building values (NULL, 'SDI Defense');
insert into building values (NULL, 'SS Component');
insert into building values (NULL, 'SS Module');
insert into building values (NULL, 'SS Structural');
insert into building values (NULL, 'Sewer System');
insert into building values (NULL, 'Solar Plant');
insert into building values (NULL, 'Stock Exchange');
insert into building values (NULL, 'Superhighways');
insert into building values (NULL, 'Supermarket');
insert into building values (NULL, 'Temple');
insert into building values (NULL, 'University');

insert into technology values (NULL, 'Advanced Flight', 'Modern', 'Applied');
insert into technology values (NULL, 'Alphabet', 'Ancient', 'Academic');
insert into technology values (NULL, 'Amphibious Warfare', 'Modern', 'Military');
insert into technology values (NULL, 'Astronomy', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Atomic Theory', 'Industrial Revolution', 'Academic');
insert into technology values (NULL, 'Automobile', 'Modern', 'Applied');
insert into technology values (NULL, 'Banking', 'Renaissance', 'Economic');
insert into technology values (NULL, 'Bridge Building', 'Ancient', 'Applied');
insert into technology values (NULL, 'Bronze Working', 'Ancient', 'Applied');
insert into technology values (NULL, 'Ceremonial Burial', 'Ancient', 'Social');
insert into technology values (NULL, 'Chemistry', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Chivalry', 'Renaissance', 'Military');
insert into technology values (NULL, 'Code of Laws', 'Ancient', 'Social');
insert into technology values (NULL, 'Combined Arms', 'Modern', 'Military');
insert into technology values (NULL, 'Combustion', 'Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Communism', 'Industrial Revolution', 'Social');
insert into technology values (NULL, 'Computers', 'Modern', 'Applied');
insert into technology values (NULL, 'Conscription','Industrial Revolution', 'Military');
insert into technology values (NULL, 'Construction', 'Ancient', 'Applied');
insert into technology values (NULL, 'Corporation','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Currency', 'Ancient', 'Economic');
insert into technology values (NULL, 'Democracy','Industrial Revolution', 'Social');
insert into technology values (NULL, 'Economics','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Electricity','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Electronics', 'Modern', 'Applied');
insert into technology values (NULL, 'Engineering', 'Ancient', 'Applied');
insert into technology values (NULL, 'Environmentalism', 'Modern', 'Social');
insert into technology values (NULL, 'Espionage', 'Modern', 'Military');
insert into technology values (NULL, 'Explosives','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Feudalism', 'Ancient', 'Military');
insert into technology values (NULL, 'Flight','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Fundamentalism','Industrial Revolution', 'Social');
insert into technology values (NULL, 'Fusion Power', 'Modern', 'Academic');
insert into technology values (NULL, 'Future Technology', 'Modern', 'Academic');
insert into technology values (NULL, 'Genetic Engineering', 'Modern', 'Academic');
insert into technology values (NULL, 'Guerrilla Warfare', 'Modern', 'Military');
insert into technology values (NULL, 'Gunpowder', 'Renaissance', 'Military');
insert into technology values (NULL, 'Horseback Riding', 'Ancient', 'Military');
insert into technology values (NULL, 'Industrialization','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Invention', 'Renaissance', 'Applied');
insert into technology values (NULL, 'Iron Working', 'Ancient', 'Applied');
insert into technology values (NULL, 'Labor Union', 'Modern', 'Social');
insert into technology values (NULL, 'Laser', 'Modern', 'Academic');
insert into technology values (NULL, 'Leadership', 'Renaissance', 'Military');
insert into technology values (NULL, 'Literacy', 'Ancient', 'Academic');
insert into technology values (NULL, 'Machine Tools','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Magnetism', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Map Making', 'Ancient', 'Economic');
insert into technology values (NULL, 'Masonry', 'Ancient', 'Applied');
insert into technology values (NULL, 'Mass Production', 'Modern', 'Applied');
insert into technology values (NULL, 'Mathematics', 'Ancient', 'Academic');
insert into technology values (NULL, 'Medicine', 'Renaissance', 'Economic');
insert into technology values (NULL, 'Metallurgy', 'Renaissance', 'Military');
insert into technology values (NULL, 'Miniaturization', 'Modern', 'Applied');
insert into technology values (NULL, 'Mobile Warfare', 'Modern', 'Military');
insert into technology values (NULL, 'Monarchy', 'Ancient', 'Social');
insert into technology values (NULL, 'Monotheism', 'Renaissance', 'Social');
insert into technology values (NULL, 'Mysticism', 'Ancient', 'Social');
insert into technology values (NULL, 'Navigation', 'Renaissance', 'Economic');
insert into technology values (NULL, 'Nuclear Fission', 'Modern', 'Academic');
insert into technology values (NULL, 'Nuclear Power', 'Modern', 'Academic');
insert into technology values (NULL, 'Philosophy', 'Renaissance', 'Social');
insert into technology values (NULL, 'Physics', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Plastics', 'Modern', 'Applied');
insert into technology values (NULL, 'Polytheism', 'Ancient', 'Social');
insert into technology values (NULL, 'Pottery', 'Ancient', 'Economic');
insert into technology values (NULL, 'Radio', 'Modern', 'Applied');
insert into technology values (NULL, 'Railroad','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Recycling', 'Modern', 'Social');
insert into technology values (NULL, 'Refining','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Refrigeration', 'Modern', 'Economic');
insert into technology values (NULL, 'Republic', 'Ancient', 'Social');
insert into technology values (NULL, 'Robotics', 'Modern', 'Military');
insert into technology values (NULL, 'Rocketry', 'Modern', 'Military');
insert into technology values (NULL, 'Sanitation','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Seafaring', 'Ancient', 'Economic');
insert into technology values (NULL, 'Space Flight', 'Modern', 'Academic');
insert into technology values (NULL, 'Stealth', 'Modern', 'Military');
insert into technology values (NULL, 'Steam Engine','Industrial Revolution', 'Academic');
insert into technology values (NULL, 'Steel','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Superconductor', 'Modern', 'Academic');
insert into technology values (NULL, 'Tactics','Industrial Revolution', 'Military');
insert into technology values (NULL, 'Theology', 'Renaissance', 'Social');
insert into technology values (NULL, 'Theory of Gravity', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Trade', 'Ancient', 'Economic');
insert into technology values (NULL, 'University', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Warrior Code', 'Ancient', 'Military');
insert into technology values (NULL, 'Wheel', 'Ancient', 'Applied');
insert into technology values (NULL, 'Writing', 'Ancient', 'Academic');

insert into technology_prereq values (
    (select id from technology where name = 'Alphabet'),
    (select id from technology where name = 'Writing')
);