insert into building values (NULL, 'Airport');
insert into building values (NULL, 'Aqueduct');
insert into building values (NULL, 'Bank');
insert into building values (NULL, 'Barracks');
insert into building values (NULL, 'Capitalization');
insert into building values (NULL, 'Cathedral');
insert into building values (NULL, 'City Walls');
insert into building values (NULL, 'Coastal Fortress');
insert into building values (NULL, 'Colosseum');
insert into building values (NULL, 'Courthouse');
insert into building values (NULL, 'Factory');
insert into building values (NULL, 'Granary');
insert into building values (NULL, 'Harbor');
insert into building values (NULL, 'Hydro Plant');
insert into building values (NULL, 'Library');
insert into building values (NULL, 'Mfg. Plant');
insert into building values (NULL, 'Marketplace');
insert into building values (NULL, 'Mass Transit');
insert into building values (NULL, 'Nuclear Plant');
insert into building values (NULL, 'Offshore Platform');
insert into building values (NULL, 'Palace');
insert into building values (NULL, 'Police Station');
insert into building values (NULL, 'Port Facility');
insert into building values (NULL, 'Power Plant');
insert into building values (NULL, 'Recycling Center');
insert into building values (NULL, 'Research Lab');
insert into building values (NULL, 'SAM Missile Battery');
insert into building values (NULL, 'SDI Defense');
insert into building values (NULL, 'SS Component');
insert into building values (NULL, 'SS Module');
insert into building values (NULL, 'SS Structural');
insert into building values (NULL, 'Sewer System');
insert into building values (NULL, 'Solar Plant');
insert into building values (NULL, 'Stock Exchange');
insert into building values (NULL, 'Superhighways');
insert into building values (NULL, 'Supermarket');
insert into building values (NULL, 'Temple');
insert into building values (NULL, 'University');

insert into technology values (NULL, 'Advanced Flight', 'Modern', 'Applied');
insert into technology values (NULL, 'Alphabet', 'Ancient', 'Academic');
insert into technology values (NULL, 'Amphibious Warfare', 'Modern', 'Military');
insert into technology values (NULL, 'Astronomy', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Atomic Theory', 'Industrial Revolution', 'Academic');
insert into technology values (NULL, 'Automobile', 'Modern', 'Applied');
insert into technology values (NULL, 'Banking', 'Renaissance', 'Economic');
insert into technology values (NULL, 'Bridge Building', 'Ancient', 'Applied');
insert into technology values (NULL, 'Bronze Working', 'Ancient', 'Applied');
insert into technology values (NULL, 'Ceremonial Burial', 'Ancient', 'Social');
insert into technology values (NULL, 'Chemistry', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Chivalry', 'Renaissance', 'Military');
insert into technology values (NULL, 'Code of Laws', 'Ancient', 'Social');
insert into technology values (NULL, 'Combined Arms', 'Modern', 'Military');
insert into technology values (NULL, 'Combustion', 'Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Communism', 'Industrial Revolution', 'Social');
insert into technology values (NULL, 'Computers', 'Modern', 'Applied');
insert into technology values (NULL, 'Conscription','Industrial Revolution', 'Military');
insert into technology values (NULL, 'Construction', 'Ancient', 'Applied');
insert into technology values (NULL, 'Corporation','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Currency', 'Ancient', 'Economic');
insert into technology values (NULL, 'Democracy','Industrial Revolution', 'Social');
insert into technology values (NULL, 'Economics','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Electricity','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Electronics', 'Modern', 'Applied');
insert into technology values (NULL, 'Engineering', 'Ancient', 'Applied');
insert into technology values (NULL, 'Environmentalism', 'Modern', 'Social');
insert into technology values (NULL, 'Espionage', 'Modern', 'Military');
insert into technology values (NULL, 'Explosives','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Feudalism', 'Ancient', 'Military');
insert into technology values (NULL, 'Flight','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Fundamentalism','Industrial Revolution', 'Social');
insert into technology values (NULL, 'Fusion Power', 'Modern', 'Academic');
insert into technology values (NULL, 'Future Technology', 'Modern', 'Academic');
insert into technology values (NULL, 'Genetic Engineering', 'Modern', 'Academic');
insert into technology values (NULL, 'Guerrilla Warfare', 'Modern', 'Military');
insert into technology values (NULL, 'Gunpowder', 'Renaissance', 'Military');
insert into technology values (NULL, 'Horseback Riding', 'Ancient', 'Military');
insert into technology values (NULL, 'Industrialization','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Invention', 'Renaissance', 'Applied');
insert into technology values (NULL, 'Iron Working', 'Ancient', 'Applied');
insert into technology values (NULL, 'Labor Union', 'Modern', 'Social');
insert into technology values (NULL, 'Laser', 'Modern', 'Academic');
insert into technology values (NULL, 'Leadership', 'Renaissance', 'Military');
insert into technology values (NULL, 'Literacy', 'Ancient', 'Academic');
insert into technology values (NULL, 'Machine Tools','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Magnetism', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Map Making', 'Ancient', 'Economic');
insert into technology values (NULL, 'Masonry', 'Ancient', 'Applied');
insert into technology values (NULL, 'Mass Production', 'Modern', 'Applied');
insert into technology values (NULL, 'Mathematics', 'Ancient', 'Academic');
insert into technology values (NULL, 'Medicine', 'Renaissance', 'Economic');
insert into technology values (NULL, 'Metallurgy', 'Renaissance', 'Military');
insert into technology values (NULL, 'Miniaturization', 'Modern', 'Applied');
insert into technology values (NULL, 'Mobile Warfare', 'Modern', 'Military');
insert into technology values (NULL, 'Monarchy', 'Ancient', 'Social');
insert into technology values (NULL, 'Monotheism', 'Renaissance', 'Social');
insert into technology values (NULL, 'Mysticism', 'Ancient', 'Social');
insert into technology values (NULL, 'Navigation', 'Renaissance', 'Economic');
insert into technology values (NULL, 'Nuclear Fission', 'Modern', 'Academic');
insert into technology values (NULL, 'Nuclear Power', 'Modern', 'Academic');
insert into technology values (NULL, 'Philosophy', 'Renaissance', 'Social');
insert into technology values (NULL, 'Physics', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Plastics', 'Modern', 'Applied');
insert into technology values (NULL, 'Polytheism', 'Ancient', 'Social');
insert into technology values (NULL, 'Pottery', 'Ancient', 'Economic');
insert into technology values (NULL, 'Radio', 'Modern', 'Applied');
insert into technology values (NULL, 'Railroad','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Recycling', 'Modern', 'Social');
insert into technology values (NULL, 'Refining','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Refrigeration', 'Modern', 'Economic');
insert into technology values (NULL, 'Republic', 'Ancient', 'Social');
insert into technology values (NULL, 'Robotics', 'Modern', 'Military');
insert into technology values (NULL, 'Rocketry', 'Modern', 'Military');
insert into technology values (NULL, 'Sanitation','Industrial Revolution', 'Economic');
insert into technology values (NULL, 'Seafaring', 'Ancient', 'Economic');
insert into technology values (NULL, 'Space Flight', 'Modern', 'Academic');
insert into technology values (NULL, 'Stealth', 'Modern', 'Military');
insert into technology values (NULL, 'Steam Engine','Industrial Revolution', 'Academic');
insert into technology values (NULL, 'Steel','Industrial Revolution', 'Applied');
insert into technology values (NULL, 'Superconductor', 'Modern', 'Academic');
insert into technology values (NULL, 'Tactics','Industrial Revolution', 'Military');
insert into technology values (NULL, 'Theology', 'Renaissance', 'Social');
insert into technology values (NULL, 'Theory of Gravity', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Trade', 'Ancient', 'Economic');
insert into technology values (NULL, 'University', 'Renaissance', 'Academic');
insert into technology values (NULL, 'Warrior Code', 'Ancient', 'Military');
insert into technology values (NULL, 'Wheel', 'Ancient', 'Applied');
insert into technology values (NULL, 'Writing', 'Ancient', 'Academic');

insert into technology_prereq values (
    (select id from technology where name = 'Alphabet'),
    (select id from technology where name = 'Writing')
);

insert into unit values (NULL, 'AEGIS Cruiser', 100, 8, 8, 3, 2, 5, 'Rocketry', 'N/A');
insert into unit values (NULL, 'Alpine Troops', 50, 5, 5, 2, 1, 1, 'Tactics', 'N/A');
insert into unit values (NULL, 'Archers', 30, 3, 2, 1, 1, 1, 'Warrior Code', 'Gunpowder');
insert into unit values (NULL, 'Armor', 80, 10, 5, 3, 1, 3, 'Mobile Warfare', 'N/A');
insert into unit values (NULL, 'Artillery', 50, 10, 1, 2, 2, 1, 'Machine Tools', 'Robotics');
insert into unit values (NULL, 'Battleship', 160, 12, 12, 4, 2, 4, 'Automobile', 'N/A');
insert into unit values (NULL, 'Bomber', 120, 12, 1, 2, 2, 8, 'Advanced Flight', 'Stealth');
insert into unit values (NULL, 'Cannon', 40, 8, 1, 2, 1, 1, 'Metallurgy', 'Machine Tools');
insert into unit values (NULL, 'Caravan', 50, 0, 1, 1, 1, 1, 'Trade', 'The Corporation');
insert into unit values (NULL, 'Caravel', 40, 2, 1, 1, 1, 3, 'Navigation', 'Magnetism');
insert into unit values (NULL, 'Carrier', 160, 1, 9, 4, 2, 5, 'Advanced Flight', 'N/A');
insert into unit values (NULL, 'Catapult', 40, 6, 1, 1, 1, 1, 'Mathematics', 'Metallurgy');
insert into unit values (NULL, 'Cavalry', 60, 8, 3, 2, 1, 2, 'Leadership', 'Mobile Warfare');
insert into unit values (NULL, 'Chariot', 30, 3, 1, 1, 1, 2, 'The Wheel', 'Polytheism');
insert into unit values (NULL, 'Cruise Missile', 60, 18, 0, 1, 3, 12, 'Rocketry', 'N/A');
insert into unit values (NULL, 'Cruiser', 80, 6, 6, 3, 2, 5, 'Steel', 'Rocketry');
insert into unit values (NULL, 'Crusaders', 40, 5, 1, 1, 1, 2, 'Monotheism', 'Leadership');
insert into unit values (NULL, 'Destroyer', 60, 4, 4, 3, 1, 6, 'Electricity', 'N/A');
insert into unit values (NULL, 'Diplomat', 30, 0, 0, 1, 1, 2, 'Writing', 'Espionage');
insert into unit values (NULL, 'Dragoons', 50, 5, 2, 2, 1, 2, 'Leadership', 'Tactics');
insert into unit values (NULL, 'Elephant', 40, 4, 1, 1, 1, 2, 'Polytheism', 'Monotheism');
insert into unit values (NULL, 'Engineers', 40, 0, 2, 2, 1, 2, 'Explosives', 'N/A');
insert into unit values (NULL, 'Explorer', 30, 0, 1, 1, 1, 1, 'Seafaring', 'Guerrilla Warfare');
insert into unit values (NULL, 'Fanatics', 20, 4, 4, 2, 1, 1, 'Fundamentalism', 'N/A');
insert into unit values (NULL, 'Fighter', 60, 4, 3, 2, 2, 10, 'Flight', 'Stealth');
insert into unit values (NULL, 'Freight', 50, 0, 1, 1, 1, 2, 'The Corporation', 'N/A');
insert into unit values (NULL, 'Frigate', 50, 4, 2, 2, 1, 4, 'Magnetism', 'Electricity');
insert into unit values (NULL, 'Galleon', 40, 0, 2, 2, 1, 4, 'Magnetism', 'Industrialization');
insert into unit values (NULL, 'Helicopter', 100, 10, 3, 2, 2, 6, 'Combined Arms', 'N/A');
insert into unit values (NULL, 'Horsemen', 20, 2, 1, 1, 1, 2, 'Horseback Riding', 'Chivalry');
insert into unit values (NULL, 'Howitzer', 70, 12, 2, 3, 2, 2, 'Robotics', 'N/A');
insert into unit values (NULL, 'Ironclad', 60, 4, 4, 3, 1, 4, 'Steam Engine', 'Electricity');
insert into unit values (NULL, 'Knights', 40, 4, 2, 1, 1, 2, 'Chivalry', 'Leadership');
insert into unit values (NULL, 'Legion', 40, 4, 2, 1, 1, 1, 'Iron Working', 'Gunpowder');
insert into unit values (NULL, 'Marines', 60, 8, 5, 2, 1, 1, 'Amphibious Warfare', 'N/A');
insert into unit values (NULL, 'Mechanized Infantry', 50, 6, 6, 3, 1, 3, 'Labor Union', 'N/A');
insert into unit values (NULL, 'Musketeers', 30, 3, 3, 2, 1, 1, 'Gunpowder', 'Conscription');
insert into unit values (NULL, 'Nuclear Missile', 160, 99, 0, 1, 1, 16, 'Rocketry', 'N/A');
insert into unit values (NULL, 'Paratroopers', 60, 6, 4, 2, 1, 1, 'Combined Arms', 'N/A');
insert into unit values (NULL, 'Partisans', 50, 4, 4, 2, 1, 1, 'Guerrilla Warfare', 'N/A');
insert into unit values (NULL, 'Phalanx', 20, 1, 2, 1, 1, 1, 'Bronze Working', 'Feudalism');
insert into unit values (NULL, 'Pikemen', 20, 1, 2, 1, 1, 1, 'Feudalism', 'Gunpowder');
insert into unit values (NULL, 'Riflemen', 40, 5, 4, 2, 1, 1, 'Conscription', 'N/A');
insert into unit values (NULL, 'Settlers', 40, 0, 1, 2, 1, 1, 'N/A', 'Explosives');
insert into unit values (NULL, 'Spy', 30, 0, 0, 1, 1, 3, 'Espionage', 'None');
insert into unit values (NULL, 'Stealth Bomber', 160, 14, 5, 2, 2, 12, 'Stealth', 'N/A');
insert into unit values (NULL, 'Stealth Fighter', 80, 8, 4, 2, 2, 14, 'Stealth', 'N/A');
insert into unit values (NULL, 'Submarine', 60, 10, 2, 3, 2, 3, 'Combustion', 'N/A');
insert into unit values (NULL, 'Transport', 50, 0, 3, 3, 1, 5, 'Industrialization', 'N/A');
insert into unit values (NULL, 'Trireme', 40, 1, 1, 1, 1, 3, 'Map Making', 'Navigation');
insert into unit values (NULL, 'Warriors', 10, 1, 1, 1, 1, 1, 'N/A', 'Feudalism');
